// Blueshore skin for the Zimbra Classic web client
// Copyright (C) 2026 Gianluca Zamagni, Parvati Srl
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your
// option) any later version. See the LICENSE file for details.
/*
 * blueshore progressive enhancement (skin-local, no core patches).
 *
 * Idempotent and driven by a MutationObserver: whenever Zimbra re-renders a
 * piece of UI, the plain form comes back and gets re-enhanced. Five tasks:
 *
 * 1. Folder unread/item counts: the Classic tree renders them inline in the
 *    label text, "Inbox (2)" inside a single SPAN. To reproduce the design
 *    (name left, count right-aligned in accent colour) the count is split
 *    into its own badge span at render time, only when the number matches
 *    the folder model (a folder may be called "Budget (2026)"). Styling
 *    lives in skin.css ([data-bs-unread]).
 * 2. Empty-state placeholder ("To view...") stretched to full height so the
 *    CSS can centre it vertically.
 * 3. Legacy avatar <img> src swapped with the svg map window.BlueshoreImgSwap
 *    generated by gen-icons.py (img/images.css.js).
 * 4. "New" button menu re-aligned to the button's right edge, synchronously
 *    inside the MutationObserver callback (a debounce shows as a visible
 *    jump).
 * 5. Standard folder/tag colour palette applied to ZmOrganizer.COLOR_VALUES
 *    and ZmMsg.color* from window.BlueshoreColorValues (Tag*C tokens).
 */
(function() {
	var RE = /^(.*) \((\d+)\)$/;

	// The count Zimbra appends to a tree label, read from the organizer behind
	// the DOM node: unread messages, or the total for Drafts and Outbox. null
	// when the node has no model (the text is then left as it is).
	function modelCount(el) {
		var Ctl = window.DwtControl, F = window.ZmFolder;
		var ctl = Ctl && Ctl.findControl ? Ctl.findControl(el) : null;
		var org = ctl && ctl.getData && window.Dwt ? ctl.getData(Dwt.KEY_OBJECT) : null;
		if (!org) { return null; }
		if (F && (org.nId == F.ID_DRAFTS || org.nId == F.ID_OUTBOX || org.rid == F.ID_DRAFTS)) {
			return org.numTotal;
		}
		return org.numUnread;
	}

	function enhance() {
		// empty state ("To view...") vertically centred: between the sized
		// view and the table sits an anonymous auto-height wrapper; an
		// equivalent CSS rule makes the server-side CSS generator fail (HTTP 500)
		var empties = document.querySelectorAll("TD.NoResults");
		for (var j = 0; j < empties.length; j++) {
			var tbl = empties[j].closest ? empties[j].closest("TABLE") : null;
			if (!tbl || tbl.style.height === "100%") { continue; }
			tbl.style.height = "100%";
			tbl.style.width = "100%";
			var wrap = tbl.parentElement;
			if (wrap && wrap.tagName === "DIV" && /_clear$/.test(wrap.id || "")) {
				wrap.style.height = "100%";
			}
		}

		// avatars served as <img src="/img/large/..."> with no class:
		// swap their src with the skin's svgs (map in images.css.js)
		if (window.BlueshoreImgSwap) {
			var imgs = document.getElementsByTagName("IMG");
			for (var q = 0; q < imgs.length; q++) {
				var src = imgs[q].getAttribute("src") || "";
				if (src.indexOf("data:") === 0) { continue; }
				for (var key in BlueshoreImgSwap) {
					if (src.indexOf(key) !== -1) {
						imgs[q].src = BlueshoreImgSwap[key];
						break;
					}
				}
			}
		}

		var spans = document.querySelectorAll(
			".ZmOverview .DwtTreeItem [class*='DwtTreeItem-Text'] > SPAN");
		for (var i = 0; i < spans.length; i++) {
			var span = spans[i];
			if (span.querySelector("[data-bs-unread]")) { continue; }
			var item = span.closest ? span.closest(".DwtTreeItem") : null;
			// "(n)" is a count only if the model agrees: Zimbra bolds a folder
			// whose subfolders have unread mail without appending a number, so
			// "Budget (2026)" must stay a name there
			var m = RE.exec(span.textContent);
			if (!m || String(modelCount(span)) !== m[2]) {
				if (item) { item.classList.remove("bs-has-unread"); }
				continue;
			}
			span.textContent = m[1];
			var badge = document.createElement("SPAN");
			badge.setAttribute("data-bs-unread", "1");
			badge.textContent = m[2];
			span.appendChild(badge);
			if (item) { item.classList.add("bs-has-unread"); }
		}
	}

	// "New" button menu: Zimbra opens it aligned to the left edge while the
	// chevron sits on the right — re-align the menu's right edge to the
	// button's right edge. Called SYNCHRONOUSLY from the observer callback
	// (pre-paint), otherwise the jump is visible.
	function alignNewMenu() {
		var btn = document.getElementById("zb__NEW_MENU");
		if (!btn) { return; }
		var br = btn.getBoundingClientRect();
		var menus = document.querySelectorAll("[id^='POPUP_']");
		for (var k = 0; k < menus.length; k++) {
			var mr = menus[k].getBoundingClientRect();
			if (mr.width > 0 && Math.abs(mr.left - br.left) < 12 &&
					mr.top >= br.bottom - 2 && mr.top <= br.bottom + 16) {
				var want = Math.round(br.right - mr.width);
				if (Math.abs(mr.left - want) > 2) {
					menus[k].style.left = want + "px";
				}
			}
		}
	}

	// Standard folder/tag/calendar colours: the client tints the composites
	// with the RGB values of ZmMsg.color* (ZmOrganizer.COLOR_VALUES table),
	// not with the skin — the stock yellow is unreadable on light surfaces.
	// Replaced with the token palette (map generated in images.css.js).
	// Idempotent and called SYNCHRONOUSLY on every mutation: it must run
	// before the tree renders.
	var COLOR_ORDER = [null, "blue", "cyan", "green", "purple", "red",
	                   "yellow", "pink", "gray", "orange"];
	function applyOrganizerColors() {
		var map = window.BlueshoreColorValues, org = window.ZmOrganizer;
		if (!map || !org || !org.COLOR_VALUES || org.COLOR_VALUES.bsApplied) { return; }
		for (var i = 1; i < COLOR_ORDER.length; i++) {
			var name = COLOR_ORDER[i], c = map[name];
			if (!c) { continue; }
			org.COLOR_VALUES[i] = c;
			if (window.ZmMsg) {
				ZmMsg["color" + name.charAt(0).toUpperCase() + name.slice(1)] = c;
			}
		}
		org.COLOR_VALUES.bsApplied = true;
	}

	var scheduled = false;
	function schedule() {
		if (scheduled) { return; }
		scheduled = true;
		setTimeout(function() { scheduled = false; try { enhance(); } catch (e) {} }, 60);
	}

	function onMutations(list) {
		try { applyOrganizerColors(); } catch (e) {}
		for (var i = 0; i < list.length; i++) {
			var t = list[i].target;
			if (t && t.id && t.id.indexOf("POPUP_") === 0) {
				try { alignNewMenu(); } catch (e) {}
				break;
			}
		}
		schedule();
	}

	function start() {
		try {
			applyOrganizerColors();
			new MutationObserver(onMutations).observe(document.body, {
				childList: true, subtree: true, characterData: true,
				attributes: true, attributeFilter: ["style"]
			});
			schedule();
		} catch (e) {}
	}

	if (document.body) { start(); }
	else { document.addEventListener("DOMContentLoaded", start); }
})();
